### PR TITLE
fix error logout when session token expired time #132

### LINKED ISSUE #132: セッショントークンの有効期限切れ時にlogoutが意図通りに完了しない
- すでにセッショントークンが期限切れかシステム側で消されている場合、リクエストエラーで処理が終了するため、無効にも関わらずインスタンスのセッショントークンが残り続ける
- セッショントークンがなければlogoutリクエストは成功しない（そもそも必要ない）ので、E401001エラーのときにインスタンスのsessionTokenを削除する処理を追加すれば解決できると思われる

### PR DESCRIPTION
**Pull request by hocnguyen**
## 概要(Summary)
- Fixed #132 セッショントークンの有効期限切れ時にlogoutが意図通りに完了しない
## 動作確認手順(Step for Confirmation)

Run the unit test.

### CODE REVIEW

**Comment by ykokw** [comment]
@hocnguyen 
Thank you for creating p-r!

Could you separate p-r for issue #161 or add description in p-r summary ?
And I can't find test code for this fixing.

**Comment by hocnguyen** [comment]
@ykokw 
Thanks for your review. 
I will separate  to 2 p-r.

**Comment by hocnguyen** [comment]
@ykokw 
I remove the code of issue 161. 
This is only code fixing of issue 132.
Please help me review again!

**Comment by ykokw** [comment]
@hocnguyen 
I've confirmed that your fixing is separated to 2 p-r. Thanks.
Could you add test code or tell me procedure for confirmation?

**Comment by hocnguyen** [comment]
@ykokw 
About this issue,   when we call logout function with a session token was expired or wrong.
The error will appear. 
Base from description of issue. I reset session info  to null value when error code response is 401.
Because In mbaas.yml file, we had declare logout function with response 200.
So I can\`t create response 401 with logout function from test code.  
That is reason i can\`t add the test code.
But Please see example code bellow. That is my code test on this issue : 
```
var user = new ncmb.User({userName:"Yamada Tarou", password:"password"});
			ncmb.User.login(user)
				.then(function(data){
                                   // reset wrong token to error appear when logout 
				    user.sessionToken="wrong token"; 
				    user.logout(function(err, res){
					  if(err){
						console.log(err);
					  }
					});
				})
				.catch(function(err){
				  // エラー処理
				});
```

**Comment by ykokw** [comment]
> Because In mbaas.yml file, we had declare logout function with response 200.

上記、mbaas.ymlに401エラーが返るスタブを用意することで

- セッショントークンが期限切れなどで401エラーが返る場合に、ローカルにあるsessionTokenが削除されることを確認する

テストコードが実装可能になるかと思います。

**Pull request merged**
